// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// GET provides a mock function with given fields: uri, f
func (_m *Router) GET(uri string, f func(http.ResponseWriter, *http.Request)) {
	_m.Called(uri, f)
}

// POST provides a mock function with given fields: uri, f
func (_m *Router) POST(uri string, f func(http.ResponseWriter, *http.Request)) {
	_m.Called(uri, f)
}

// SERVE provides a mock function with given fields: port
func (_m *Router) SERVE(port string) {
	_m.Called(port)
}
